baseurl = "http://mettleup.dev/blog"
title = "Mettle Blog"
canonifyurls = true
paginate = 10
theme = "mettleup-blog"
languageCode = "en-us"
copyright = "<a href=\"http://mettleup.com\">Mettle LLC</a>. All rights reserved."

[author]
  name = "Mettle"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Superior Web Application Development"
  Author = "Mettle"
  email = "info@mettleup.com"
  Ganalytics = "UA-1446018-11"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/mettleup"
[[params.social]]
  title = "github"
  url = "https://github.com/mettleup"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/MettleUp"

[[menu.main]]
  name = "home"
  url = "http://mettleup.com"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Contact"
  url = "mailto:info@mettleup.com"
  weight = -160
