baseurl = "http://mettleup.dev/blog"
title = "Mettle Blog"
canonifyurls = true
paginate = 10
theme = "mettleup-blog"
languageCode = "en-us"
copyright = "[Mettle LLC](http://mettleup.com). All rights reserved."

[permalinks]
    post = "/:title/"

[author]
  name = "Mettle"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Superior Web Application Development"
  Author = "Mettle"
  email = "info@mettleup.com"
  Ganalytics = "UA-1446018-11"

[params.authors]
    [params.authors.andy]
        name = "Andy Soell"
        image = "http://www.gravatar.com/avatar/710af8381d42de7cfbc1bdfbcdbfaa4b?s=200"
        bio = "Andy Soell is the co-founder and lead backend architect at [Mettle](http://mettleup.com), an exceptional software development studio. Andy lives with his wife, daughter and border collie in Prague and when he isn't scrutinizing his code for more ways to make it even faster he can usually be found at a coffee shop with a good book."
        twitter = "amsoell"

    [params.authors.rory]
        name = "Rory Garand"
        image = "http://www.gravatar.com/avatar/15525a3a1891dcfe2d38c6338c407836?s=200"
        bio = "When he isn't building complex frontend web application interfaces, Rory is usually digging into the latest JavaScript framework to see how it stacks up to what's already out there. As one of [Mettle's](http://mettleup.com) co-founders, Rory heads up Mettle's frontend web application efforts and takes lead on engineering how the user will interact with every step of the project's interface, making every application we build a joy to work with."
        twitter = "rorygarand"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/mettleup"
[[params.social]]
  title = "github"
  url = "https://github.com/mettleup"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/MettleUp"


[[menu.main]]
  name = "home"
  url = "http://mettleup.com"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Contact"
  url = "mailto:info@mettleup.com"
  weight = -160
