baseurl = "http://mettleup.dev/blog"
title = "Mettle :: What's On Our Minds"
canonifyurls = true
paginate = 10
theme = "mettleup-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Mettle"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Superior Web Application Development"
  Author = "Mettle"
  email = "info@mettleup.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/mettleup"
[[params.social]]
  title = "github"
  url = "https://github.com/mettleup"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/MettleUp"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
