name = "Mettle Blog"
license = "Apache 2.0"
licenselink = "https://github.com/humboldtux/startbootstrap-clean-blog/blob/master/LICENSE.md"
description = "Mettle Blog"
homepage = "https://mettleup.com"
tags = ["blog", "bootstrap"]
features = ["blog", "bootstrap"]
min_version = 0.14

[author]
  name = "Andy Soell"
  homepage = "http://mettleup.com"

# original theme
[original]
  name = "Startbootstrap Clean Blog"
  homepage = "http://startbootstrap.com/template-overviews/clean-blog/"
  repo = "https://github.com/IronSummitMedia/startbootstrap-clean-blog"
